export const ACCESS_REQUEST_SYSTEM_ENTITLEMENTS = {
  ACTIVE_DIRECTORY: ['AUDIT_LOG_DELETE', 'AUDIT_LOG_BYPASS'],
  AI_MODEL_REGISTRY: ['AI_MODEL_QUERY', 'AI_MODEL_FINE_TUNE'],
  ARTIFACT_PACKAGE_REGISTRY: ['PACKAGE_PUBLISH_PROD'],
  CLOUD_INFRASTRUCTURE: [
    'DEV_CODE_COMMIT',
    'DEV_CODE_APPROVER',
    'AWS_PROD_WRITE',
    'INFRA_BREAK_GLASS',
  ],
  CRM_SYSTEM: ['CRM_LEAD_EDIT', 'CRM_TICKET_EDIT', 'CRM_CAMPAIGN_READ'],
  CUSTOMER_360_DB: ['CRM_EXPORT_BULK', 'CRM_CREDIT_CARD_VIEW'],
  DATA_WAREHOUSE: ['FIN_DATASET_READ'],
  EDR_HOST_PLATFORM: ['EDR_HOST_ISOLATE'],
  FINANCE_ANALYTICS_DB: ['FIN_DATASET_EDIT', 'FIN_BILLING_EXPORT'],
  FIREWALL_RULE_ENGINE: ['FIREWALL_RULE_EDIT'],
  GITHUB_ENTERPRISE_TENANT: ['REPO_READ_PUBLIC', 'REPO_ADMIN_DELETE'],
  HRIS_WORKDAY: ['HR_EMPLOYEE_DIRECTORY_READ', 'HR_COMPLIANCE_VIEW', 'HR_PII_FULL_ACCESS'],
  IDP_DIRECTORY: ['IDP_USER_MANAGER', 'IDP_ADMIN'],
  KUBERNETES_CLUSTER: ['SEC_AUDIT_READ'],
  LLM_PROMPT_GATEWAY: ['AI_SAFETY_BYPASS'],
  OKTA_AUTH0_TENANT: ['IDP_AUDITOR'],
  PAYROLL_SYSTEM: [
    'PAYROLL_RECORD_READ',
    'PAYROLL_COMPENSATION_EDIT',
    'PAYROLL_DISBURSEMENT_APPROVE',
  ],
  PROD_DEPLOYMENT_PIPELINE: ['PROD_DEPLOYER', 'STAGING_DEPLOYER'],
  RAW_ANALYTICS_LAKE: ['DATA_SCIENCE_READ', 'MKT_DATASET_READ'],
  SIEM_LOG_AGGREGATOR: ['SIEM_LOG_READ', 'SOC_ALERT_DISMISS'],
  SOURCE_CODE_VAULT: ['PROPRIETARY_CORE_SRC_READ'],
  STRIPE_PAYMENT_GATEWAY: ['PAYMENT_GATEWAY_REFUND'],
  SUPPLY_CHAIN_ERP: ['SUPPLY_CHAIN_ORDER_EDIT'],
  SWIFT_WIRE_SYSTEM: ['WIRE_TRANSFER_INITIATE', 'WIRE_TRANSFER_APPROVE'],
  THIRD_PARTY_WEBHOOK_INGRESS: ['VENDOR_INTEGRATION_CREATE', 'WEBHOOK_SECRET_ROTATE'],
  TREASURY_BANK_PORTAL: ['TREASURY_VIEW'],
  VENDOR_API_GATEWAY: ['VENDOR_API_KEY_READ'],
} as const;

export type AccessRequestSystemName = keyof typeof ACCESS_REQUEST_SYSTEM_ENTITLEMENTS;

export const ACCESS_REQUEST_SYSTEM_NAMES = Object.keys(
  ACCESS_REQUEST_SYSTEM_ENTITLEMENTS,
).sort() as AccessRequestSystemName[];

export function isAccessRequestCatalogMember(value: string, catalog: readonly string[]): boolean {
  return catalog.includes(value.trim());
}

export function getEntitlementKeysForSystem(systemName: string): readonly string[] {
  const trimmedSystemName = systemName.trim();
  if (!isAccessRequestCatalogMember(trimmedSystemName, ACCESS_REQUEST_SYSTEM_NAMES)) {
    return [];
  }
  return ACCESS_REQUEST_SYSTEM_ENTITLEMENTS[trimmedSystemName as AccessRequestSystemName];
}

export function isValidSystemEntitlementPair(systemName: string, entitlementKey: string): boolean {
  return getEntitlementKeysForSystem(systemName).includes(entitlementKey.trim());
}
